Repository Accruent/robotframework-zoomba, pull requests merged in 2022-04, with the labels that each got.

#271 Test retry logic in GitHub Actions
  .github/workflows/run-tests.yml
  docs/APILibraryDocumentation.html
  docs/DesktopLibraryDocumentation.html
  docs/GUILibraryDocumentation.html
  docs/MobileLibraryDocumentation.html
  docs/SOAPLibraryDocumentation.html
Labels: tech debt

#272 force integer comparison added
  docs/APILibraryDocumentation.html
  docs/DesktopLibraryDocumentation.html
  docs/GUILibraryDocumentation.html
  docs/MobileLibraryDocumentation.html
  docs/SOAPLibraryDocumentation.html
  src/Zoomba/APILibrary.py
  test/API/APITests.robot
  test/API/test_validate.py
Labels: bug

#273 update DesktopLibrary docs
  docs/APILibraryDocumentation.html
  docs/DesktopLibraryDocumentation.html
  docs/GUILibraryDocumentation.html
  docs/MobileLibraryDocumentation.html
  docs/SOAPLibraryDocumentation.html
  src/Zoomba/DesktopLibrary.py
Labels: docs
